SeyahatSitesi/Models/Entity/Anasayfa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SeyahatSitesi.Models.Siniflar
{
    public class Anasayfa
    {   [Key]
        public int ID { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
    }
}

SeyahatSitesi/Controllers/AnasayfaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SeyahatSitesi.Models.Siniflar;

namespace SeyahatSitesi.Controllers
{
    public class AnasayfaController : Controller
    {
        Context db = new Context();
        Blog bl = new Blog();

        public ActionResult Index()
        {
            var degerler = db.Blogs.ToList();
            return View(degerler);
        }



        public PartialViewResult Partial1()
        {
            var degerler = db.Blogs.OrderByDescending(x => x.ID).Take(2).ToList();
            return PartialView(degerler);
        }

        public PartialViewResult Partial2()
        {
            var degerler = db.Blogs.Where(x => x.ID == 1).ToList();
            return PartialView(degerler);
        }

        public PartialViewResult Partial3()
        {
            var degerler = db.Blogs.Take(10).ToList();
            return PartialView(degerler);
        }

        public PartialViewResult Partial4()
        {
            var degerler = db.Blogs.Take(3).ToList();
            return PartialView(degerler);
        }
        public PartialViewResult Partial5()
        {
            var degerler = db.Blogs.Take(3).OrderByDescending(x => x.ID).ToList();
            return PartialView(degerler);
        }
    }
}

SeyahatSitesi/Views/Anasayfa/Index.cshtml
@using SeyahatSitesi.Models.Siniflar
@model List<Blog>
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>

<body>
    
    
    <div class="header-banner">
        <div class="wrap">
            <div class="banner">
                <div class="indent">
                    <h2 class="indent-left margin-bot">Plan the Easy Trip</h2>
                    <div class="banner-left">
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/glass.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Restaurants</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/flight.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Flights</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/group.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Things to do</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/key.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Vacation Rents</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="header_bottom_right_images">

                        <div class="slider">
                            <ul class="rslides" id="slider1">
                                <li><img src="~/web/images/img1.jpg" alt=""></li>
                                <li><img src="~/web/images/img2.jpg" alt=""></li>
                                <li><img src="~/web/images/img3.jpg" alt=""></li>
                                <li><img src="~/web/images/img4.jpg" alt=""></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class"content">
        <div class="wrap">
            <div class="wrapper">
                <div class="con-top">
                    <h3>Welcome to our Travel Company!</h3>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facil</p>
                </div>
                <div class="con-bot">
                    <div class="left">
                        <div class="bot-left">
                            <img src="~/web/images/pic.jpg" alt="" />
                        </div>
                        <div class="left-text">
                            <h4>Lorem ipsum dolor sit amet, conte adipiscing elit dolor sit amet</h4>
                            <span class="doller">$1024.99</span>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismo</p>
                            <p><a href="#"><span class="read">Read More >></span></a></p>
                        </div>
                    </div>
                    <div class="left">
                        <div class="bot-left">
                            <img src="~/web/images/pic1.jpg" alt="" />
                        </div>
                        <div class="left-text">
                            <h4>Lorem ipsum dolor sit amet, conte adipiscing elit dolor sit amet</h4>
                            <span class="doller">$900.99</span>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismo</p>
                            <p><a href="#"><span class="read">Read More >></span></a></p>
                        </div>
                    </div>
                    <div class="right">
                        <div class="bot-left">
                            <img src="~/web/images/pic2.jpg" alt="" />
                        </div>
                        <div class="left-text">

                            <h4>Lorem ipsum dolor sit amet, conte adipiscing elit dolor sit amet</h4>
                            <span class="doller">$924.99</span>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismo</p>
                            <p><a href="#"><span class="read">Read More >></span></a></p>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="grids">
                    <div class="box1">
                        <div class="padding">
                            <h4>This Week's Top 10</h4>
                            <ul class="list list-pad">
                                <li class="list-bg"><span>1.</span><a href="#">formas humanitatis pe</a></li>
                                <li class="list-bg1"><span>2.</span><a href="#">congue nihil imperdiet</a></li>
                                <li class="list-bg"><span>3.</span><a href="#">Aadipisicing elit sed do</a></li>
                                <li class="list-bg1"><span>4.</span><a href="#">luptatum zzril  </a></li>
                                <li class="list-bg"><span>5.</span><a href="#">Claritas est etiam</a></li>
                                <li class="list-bg1"><span>6.</span><a href="#">claritatem insitam;</a></li>
                                <li class="list-bg"><span>7.</span><a href="#">velit esse molestie consequa</a></li>
                                <li class="list-bg1"><span>8.</span><a href="#">nostrud exerci tation ulla</a></li>
                                <li class="list-bg"><span>9.</span><a href="#">demonstraverunt lectores</a></li>
                                <li class="list-bg1"><span>10.</span><a href="#">dolore te feu</a></li>
                            </ul>
                            <a href="#" class="link1">See all hotels</a>
                        </div>
                        <div class="padding1">
                            <h4>Our Best Places</h4>
                            <div class="box-left">
                                <div class="bot-img">
                                    <img src="~/web/images/pic3.jpg" alt="" />
                                </div>
                                <div class="bot-desc">
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                                </div>
                                <div class="clear"></div>
                                <div class="bot-img">
                                    <img src="images/pic7.jpg" alt="" />
                                </div>
                                <div class="bot-desc">
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                                </div>
                                <div class="clear"></div>
                                <div class="bot-img">
                                    <img src="~/web/images/pic8.jpg" alt="" />
                                </div>
                                <div class="bot-desc">
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="box1-left">
                                <div class="bot-img">
                                    <img src="~/web/images/pic9.jpg" alt="" />
                                </div>
                                <div class="bot-desc1">
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                                </div>
                                <div class="clear"></div>
                                <div class="bot-img">
                                    <img src="~/web/images/pic10.jpg" alt="" />
                                </div>
                                <div class="bot-desc1">
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                                </div>
                                <div class="clear"></div>
                                <div class="bot-img">
                                    <img src="~/web/images/pic3.jpg" alt="" />
                                </div>
                                <div class="bot-desc1">
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="wrap">
            <div class="copy">
                <p>&copy; 2013 Easy-Trip. All Rights Reserved | Design by <a href="http://w3layouts.com">W3Layouts</a></p>
            </div>
        </div>
    </div>
</body>
</html>

SeyahatSitesi/Views/Anasayfa/Partial1.cshtml
@using SeyahatSitesi.Models.Siniflar
@model List <Blog>

<div class="con-bot">
    @foreach (var x in Model)
    {

   
    <div class="left">
        <div class="bottom-left">
            <img src="@x.Blogimage" style="width:360px;height:200px;" alt="" />
        </div>
        <div class="left-text" style="text-align:justify;">
            <h4>@x.Baslik</h4>
            <span class="vertical">@x.Tarih.ToString("dd.MM.yyyy")</span>
            <p>@x.Aciklama.Substring(0,80) </p>
            <p><a href="/Blog/BlogDetay/@x.ID"><span class="read">Devamını Oku>></span></a></p>
        </div>
    </div>
    }
    @Html.Action("Partial2","Anasayfa")
    @*<div class="right">
        <div class="bot-right">
            <img src="~/web/images/pic1.jpg" alt="" />
        </div>
        <div class="left-text">
            <h4>Lorem ipsum dolor sit amet, conte adipiscing elit dolor sit amet</h4>
            <span class="doller">$900.99</span>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismo</p>
            <p><a href="#"><span class="read">Read More >></span></a></p>
        </div>
    </div>
    <div class="left">
        <div class="bot-right">
            <img src="~/web/images/pic2.jpg" alt="" />
        </div>
        <div class="left-text">

            <h4>Lorem ipsum dolor sit amet, conte adipiscing elit dolor sit amet</h4>
            <span class="doller">$924.99</span>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismo</p>
            <p><a href="#"><span class="read">Read More >></span></a></p>
        </div>
    </div>*@
    <div class="clear"></div>
</div>

SeyahatSitesi/Views/Anasayfa/Partial2.cshtml
@using SeyahatSitesi.Models.Siniflar
@model List <Blog>

@foreach (var x in Model)
{
<div class="right">
  <div class="bottom-left">
        <img src="@x.Blogimage" style="width:360px;height:200px;" alt="" />
    </div>
    <div class="left-text" style="text-align:justify;">
        <h4>@x.Baslik</h4>
        <span class="underline">@x.Tarih.ToString("dd.MM.yyyy")</span>
        <p>@x.Aciklama.Substring(0,80)</p>
        <p><a href="/Blog/BlogDetay/@x.ID"><span class="read">Devamını Oku>></span></a></p>
    </div>
   
</div>
}

SeyahatSitesi/Views/Anasayfa/Partial3.cshtml
@using SeyahatSitesi.Models.Siniflar
@model List <Blog>
<div class="padding"  >
    <h4>En Popüler 10 Blog</h4>
    <ul class="list list-pad" >
        @{int i= 0;}
        @foreach (var x in Model)
        {
            <li class="list-bg"><span>@{i++;} @i.</span><a href="#">@x.Baslik</a></li>
        }
      
        
    </ul>
    <a href="#" class="link1">Bütün Oteller</a>
</div>

SeyahatSitesi/Views/Anasayfa/Partial4.cshtml
@using SeyahatSitesi.Models.Siniflar
@model List<Blog>
<div class="padding1">
    <h4>En Beğendiğim Yerler</h4>
    <div class="box-left">
        @foreach (var x in Model)
        {

        
        <div class="bot-img">
            <img src="@x.Blogimage" style="width:120px;height:65px;" alt="" />
        </div>
        <div class="bot-desc" style="text-align:justify;">
            <p>@x.Aciklama.Substring(0,70)</p>
        </div>
       
        <div class="clear"></div>
        }
        
        
        
    </div>
     
    @Html.Action("Partial5","Anasayfa")
</div>

SeyahatSitesi/Views/Anasayfa/Partial5.cshtml
@using SeyahatSitesi.Models.Siniflar
@model List<Blog>
<div class="box1-left">
    
    @foreach (var x in Model)
    {<div class="bot-img">
            <img src="@x.Blogimage" style="width:120px;height:65px;" alt="" />
        </div>

        <div class="bot-desc1" style="text-align:justify;">
            <p>@x.Aciklama.Substring(0,70) </p>
        </div>
        <div class="clear"></div>
    }




</div>