SeyahatSitesi/Models/Entity/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SeyahatSitesi.Models.Siniflar
{
    public class Blog
    {[Key]
     public int ID { get; set; }
     public string Baslik { get; set; }
     public DateTime Tarih{ get; set; }
     public string Aciklama { get; set; }
     public string Blogimage { get; set; }
     public ICollection<Yorumlar> Yorumlars { get; set; }
    }
} 

SeyahatSitesi/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SeyahatSitesi.Models.Entity;
using SeyahatSitesi.Models.Siniflar;

namespace SeyahatSitesi.Controllers
{
    public class BlogController : Controller
    {
        Context db = new Context();
        BlogYorum by = new BlogYorum();

        public ActionResult Index()
        {
            // var degerler = db.Blogs.ToList();
            by.Deger1 = db.Blogs.ToList();
            by.Deger3 = db.Blogs.OrderByDescending(x =>x.ID).Take(2).ToList();
            by.Deger4 = db.Yorumlars.Take(3).ToList();
            return View(by);
        }

     
        public ActionResult BlogDetay(int id)
        {
            //var degerler = db.Blogs.Where(x => x.ID == id).ToList();

            by.Deger1 = db.Blogs.Where(x => x.ID == id).ToList();
            by.Deger2 = db.Yorumlars.Where(x => x.Blogid == id).ToList();
            by.Deger5 = db.Yorumlars.Where(x => x.Blogid == id).Take(2).ToList();
            return View(by);

        }
    }
}

SeyahatSitesi/Controllers/YorumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SeyahatSitesi.Models.Siniflar;

namespace SeyahatSitesi.Controllers
{ 
    public class YorumController : Controller
    { Context db = new Context();
        // GET: Yorum

        [HttpGet]
        public PartialViewResult YorumYap(int id)
        {
            ViewBag.deger = id;
            return PartialView();
        }

        [HttpPost]
        public PartialViewResult YorumYap(Yorumlar y)
        {
            db.Yorumlars.Add(y);
            db.SaveChanges();
            return PartialView();
                
                }

        

    }
}

SeyahatSitesi/Views/Blog/BlogDetay.cshtml
@model SeyahatSitesi.Models.Entity.BlogYorum


@{
    ViewBag.Title = "BlogDetay";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!DOCTYPE HTML>
<html>
<head>
    <title>Personal Blog a Blogging Category Flat Bootstarp  Responsive Website Template | Single :: w3layouts</title>
    <link href="~/web1/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web1/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    

</head>
<body>

    <div class="header">
        
    </div>
    
    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
                
                
                <div class="single-grid">
                 @foreach (var x in Model.Deger1)
                 { 
                     <img src="@x.Blogimage" alt=""  style="margin-bottom:20px"/>
                    <h1>  @x.Baslik</h1>
                    <p>
                       @x.Aciklama
                    </p>
                 }
                </div>
                
               
               @foreach (var y in Model.Deger2)
               { <ul class="comment-list">
                    
                    <li>
                        <img src="~/web1/images/avatar.png" class="img-responsive" alt="">
                        <div class="desc">
                            <p>@y.KullaniciAdi: @y.Yorum </p>
                        </div>
                        <div class="clearfix"></div>
                    </li>
                </ul>
               }
                @Html.Action("YorumYap","Yorum")
            </div>

            <div class="col-md-4 side-content">
                
                <div class="comments">
                    <h3>SON YORUMLAR</h3>
                   
                  <ul>
                 @foreach (var x in Model.Deger5)
                 {
                        <li><a href="">@x.KullaniciAdi </a> <a href="#">@x.Yorum</a></li>
                        
                 }
                    </ul>

                
                    
                </div>
                <div class="clearfix"></div>
                
                
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
   
   </body>
</html>
    

SeyahatSitesi/Views/Blog/Index.cshtml
@model SeyahatSitesi.Models.Entity.BlogYorum
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!DOCTYPE HTML>
<html>
<head>
    
    <link href="~/web1/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web1/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
   
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
   

</head>
<body>
  
    <div class="header">
        <div class="container">
            <div class="logo">
                <a href="index.html"><img src="~/web1/images/logo.jpg" title="" /></a>
            </div>
          
            
            <div class="clearfix"></div>
            <script>
					$("span.menu").click(function(){
					$(".top-menu ul").slideToggle("slow" , function(){
					});
					});
            </script>
           
        </div>
    </div>
  
    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
               @foreach (var x in Model.Deger1)
               {

              
                <div class="single-grid">
                    <img src="@x.Blogimage" alt="" style="margin-bottom:20px" />
                    <br /><br />
                    <a href="/Blog/BlogDetay/@x.ID">@x.Baslik</a>

                    <p>
                       @x.Aciklama
                    </p>
                </div>

               }
            </div>

            <div class="col-md-4 side-content">
                <div class="recent">
                    <h3>SON BLOGLAR</h3>
                    @foreach (var y in Model.Deger3)
                    {

                   
                    <ul>
                        <li><a href="/Blog/BlogDetay/@y.ID">@y.Baslik</a></li>
                        
                    </ul>
                    }
                </div>
                <div class="comments">
                    <h3>SON YORUMLAR</h3>
                    @foreach (var z in Model.Deger4)
                    {

                   
                    <ul>
                        <li><a href="/Blog/BlogDetay/@z.ID">@z.KullaniciAdi</a> </li>
                        
                    </ul>
                    }
                </div>
                <div class="clearfix"></div>
                
                
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    </div>
    <!---->
    <div class="footer">
        <div class="container">
            <p></a></p>
        </div>
    </div>
    </body>
    </html>